name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Scheduler 디렉토리가 없으면 Git 리포지토리 클론
            if [ ! -d "/home/ubuntu/Scheduler" ]; then
              git clone https://github.com/<your-username>/Scheduler.git /home/ubuntu/Scheduler
            fi

            # Scheduler 디렉토리로 이동
            cd /home/ubuntu/Scheduler

            # 최신 코드 Pull
            git pull origin main

            # Docker Compose 실행
            docker-compose down || true
            docker-compose up -d
