name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to EC2 and create .env
        run: |
          ssh -i <path_to_pem_file> ubuntu@${{ secrets.EC2_HOST }} << EOF
          cd /home/ubuntu/Scheduler
          echo "${{ secrets.ENV_VARS }}" > .env
          EOF

      - name: Deploy using Docker Compose
        run: |
          ssh -i <path_to_pem_file> ubuntu@${{ secrets.EC2_HOST }} << EOF
          cd /home/ubuntu/Scheduler
          docker-compose down
          docker-compose up --build -d
          EOF